---
###################################################################################
#     _              _ _     _        ____  _             _                 _     #
#    / \   _ __  ___(_) |__ | | ___  |  _ \| | __ _ _   _| |__   ___   ___ | | __ #
#   / _ \ | '_ \/ __| | '_ \| |/ _ \ | |_) | |/ _` | | | | '_ \ / _ \ / _ \| |/ / #
#  / ___ \| | | \__ \ | |_) | |  __/ |  __/| | (_| | |_| | |_) | (_) | (_) |   <  #
# /_/   \_\_| |_|___/_|_.__/|_|\___| |_|   |_|\__,_|\__, |_.__/ \___/ \___/|_|\_\ #
#                                                   |___/                         #
###################################################################################


- hosts: localhost
  gather_facts: no

###################################################################################
#                    __     __         _       _     _                            #
#                    \ \   / /_ _ _ __(_) __ _| |__ | | ___  ___                  #
#                     \ \ / / _` | '__| |/ _` | '_ \| |/ _ \/ __|                 #  
#                      \ V / (_| | |  | | (_| | |_) | |  __/\__ \                 #
#                       \_/ \__,_|_|  |_|\__,_|_.__/|_|\___||___/                 #
#                                                                                 #
###################################################################################

  vars:
  
  # AWS API Credentials
    #aws_access_key: ""
    #aws_secret_key: ""

  # AWS CFT stack settings
    region: eu-west-2
    stack_name: F5-BIG-IP-LAB

###################################################################################
#                               _____         _                                   #
#                              |_   _|_ _ ___| | _____                            #
#                                | |/ _` / __| |/ / __|                           #
#                                | | (_| \__ \   <\__ \                           #
#                                |_|\__,_|___/_|\_\___/                           #
#                                                                                 #
###################################################################################

  # DELETE Cloudformation stack
  tasks:
  - name: DELETE CLOUDFORMATION STACK
    cloudformation:
      #aws_access_key: "{{ aws_access_key }}"
      #aws_secret_key: "{{ aws_secret_key }}"
      stack_name: "{{ stack_name }}"
      state: absent
      region: "{{ region }}"

...